#cloud-config
---
manage_resolv_conf: true
package_update: true
package_upgrade: true
package_reboot_if_required: true
bootcmd:
  - sudo apt-get update -y

packages:
  - apt-transport-*
  - ca-certificates
  - curl
  - software-properties-common
  - git
  - net-tools
  - bridge-utils
  - dnsutils
  - bash-completion
  - tcpdump
  - wget
  - ethtool
  - screen
  - ipset
  - tmux
  - jq

write_files:
  - path: "/etc/docker/daemon.json"
    permissions: "0644"
    owner: "root"
    content: |-
      {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
         "log-opts": {
           "max-size": "100m"
         },
         "storage-driver": "overlay2"
      }
  - path: "/etc/NetworkManager/NetworkManager.conf"
    permissions: "0644"
    owner: "root"
    content: |
      [main]
      plugins=ifcfg-rh
      plugins=keyfile
      [keyfile]
      unmanaged-devices=interface-name:cali*
  - path: "/etc/apt/sources.list.d/kubernetes.list"
    permissions: "0644"
    owner: "root"
    content: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
  - path: "/etc/sysctl.d/k8s.conf"
    permissions: "0644"
    owner: "root"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  # Docker recommended settings
  - path: "/etc/sysctl.d/docker.conf"
    permissions: "0644"
    owner: "root"
    content: |
      vm.swappiness=0
      vm.overcommit_memory=1
      net.ipv4.ip_forward=1
      net.ipv4.tcp_keepalive_time=600
  - path: "/root/kubeadm/kubeadm-config.yaml"
    permissions: "0644"
    owner: "root"
    content: |-
      apiVersion: kubeadm.k8s.io/v1beta2
      kind: ClusterConfiguration
      kubernetesVersion: v1.18.8
      clusterName: kubernetes
      networking:
        serviceSubnet: 10.96.0.0/12
        podSubnet: 192.168.0.0/16
        dnsDomain: cluster.local
      apiServer:
        timeoutForControlPlane: 4m0s
      controllerManager: {}
      controlPlaneEndpoint: $MASTER_PUB_IP
      ---
      apiVersion: kubeproxy.config.k8s.io/v1alpha1
      kind: KubeProxyConfiguration
      mode: iptables

runcmd:
  - sed -i -- 's/\#PermitRootLogin\ yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
  - sed -i -- 's/\#AllowTcpForwarding\ yes/AllowTcpForwarding\ yes/g' /etc/ssh/sshd_config
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
  # install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - usermod -aG docker ubuntu
  - usermod -aG docker azureuser
  - mkdir -p /etc/systemd/system/docker.service.d
  - systemctl enable docker
  - systemctl start docker
  # install kube components
  - apt-get install -y kubelet kubeadm kubectl
  # install specific version of kube components
  # - apt-get install -y kubelet=1.18.8-00 kubeadm=1.18.8-00 kubectl
  - apt-mark hold kubelet kubeadm kubectl
  - systemctl enable kubelet && systemctl start kubelet
  # enable ecmp routes on Ubuntu 18.04+
  - echo 'net.ipv4.fib_multipath_hash_policy=1' >> /etc/sysctl.conf
  - systemctl reboot