---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: $JOIN_TOKEN
    apiServerEndpoint: "${master_private_ip}:${kube_api_port}"      # UPDATE if endpoint is not set to MASTER PRIVATE IP
    caCertHashes: ["$TOKEN_CERT_HASH"]  # UPDATE based on kubeadm init output
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws